### ISSUE TITLE
CI/CD pipeline with VSTS

### ISSUE THREAD

**Issue by jcorioland** [Azure/acs-demos#3]
The idea is to detail how it is possible to create a full CI/CD pipeline to deploy an application continuously into Azure Container Services

**Comment by SorraTheOrc** [comment]
Yes this would be a really good contribution, much like you wrote up at https://blogs.msdn.microsoft.com/jcorioland/2016/11/29/full-ci-cd-pipeline-to-deploy-multi-containers-application-on-azure-container-service-docker-swarm-using-visual-studio-team-services/

I would prefer that we don't have the CI/CD code inside the existing demo repo's (though any configuration as code stuff that should be stored against the source code is fine). The reason for this is that I'd like folks to be able to demonstrate different CI/CD solutions.

Would it work if we had a separate demo project for VSTS which had the instructions for setting it up with one of the demo projects. Once we have that we could create scripting that would build out a demo infrastructure.

**Comment by jcorioland** [comment]
Yes, we can definitely do that and just have the configuration as code stuff in the repo (like docker-compose, k8s yaml, mesos JSON, Jenkins code pipeline definition etc.) and write some MD files to help to setup the whole thing using different CI/CD systems.

**Comment by jpbriend** [comment]
Or use a separate branch for every CI/CD system.

**Comment by jcorioland** [comment]
@jpbriend yes, that's an option ! can you log an issue for the same workflow with Jenkins, please?

**Comment by SorraTheOrc** [comment]
There are many other pieces where we have multiple options (e.g. monitoring, storage, network drivers). How do we do the many combinations of each? 

I'd much rather we start of with requiring a few manual steps to integrate different options. Eventually, we can build a "demo building script" where we choose different combinations and it builds out the necessary configurations.

**Comment by jcorioland** [comment]
I have submitted PR #9
@jpbriend and I will start our work on Jenkins + k8s tomorrow !

**Comment by SorraTheOrc** [comment]
PR merged - thank you
