### ISSUE TITLE
Kubernetes Spark demo does not expose UI

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/acs-demos#32]
The Kubernetes Spark demo script says:

Spark will be available at [http://localhost:8001/api/v1/proxy/namespaces/spark-cluster/services/spark-ui-proxy/](http://localhost:8001/api/v1/proxy/namespaces/spark-cluster/services/spark-ui-proxy/).

However when I poin the browser there I get:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"spark-ui-proxy\" not found",
  "reason": "NotFound",
  "details": {
    "name": "spark-ui-proxy",
    "kind": "endpoints"
  },
  "code": 404
}

/cc @suhaildawood

**Comment by suhaildawood** [comment]
I believe the URL should be http://localhost:8001/api/v1/proxy/namespaces/spark-cluster/services/spark-master:8080/ - will create a PR

**Comment by SorraTheOrc** [comment]
No that does not appear to be correct either

**Comment by SorraTheOrc** [comment]
I can view the Spark UI if I go to the service endpoint, e.g.:

http://SERVICE_ENDPOINT_IP/proxy:spark-master:8080

However, `kubectl get pods` is showing:

`spark-ui-proxy-controller-krdc8   0/1       CrashLoopBackOff   1439       5d`

Which seems kind of strange...

**Comment by SorraTheOrc** [comment]
@suhaildawood any ideas?

**Comment by SorraTheOrc** [comment]
Fixed in #39
