### ISSUE TITLE
Broken link to SimDem in README.md

### ISSUE THREAD

**Issue by rbitia** [Azure/acs-demos#63]
https://github.com/Azure/acs-demos/blob/master/SimDem < this link doesn't work 
https://github.com/rgardler/simdem < but this one does for your simdem tool 

on the read.md for acs-demos

**Comment by SorraTheOrc** [comment]
Can you please issue a pull request so I can see this in context and merge as appropriate.

**Comment by SorraTheOrc** [comment]
This is now fixed
