### ISSUE TITLE
Not intuitively prompted for multiple inputs 

### ISSUE THREAD

**Issue by rbitia** [Azure/acs-demos#78]
When trying to create a K8 cluster or an azure container instance the command required multiple inputs but I'm only prompted for one.

**Comment by SorraTheOrc** [comment]
You mean given a command such as:

```
az acs create -g $RESOURCE_GROUP -n $CLUSTER_NAME ...
```

And 

without providing an env.json or env.local.json file (so varaibles are not initialized)

Then 

SimDem only asks for values for one of the variables.

(I know you mean this as I just reproduced it ;-)

This is a bug.

**Comment by SorraTheOrc** [comment]
Sorry... I meant to be more helpful in my reply...

This is a bug. 

WORKAROUND

Provide values in env.json or env.local.json

**Comment by SorraTheOrc** [comment]
And one more comment.... this is a bug in SimDem not ACS Demos. Closing here and opened on [SimDem](https://github.com/Azure/simdem/issues/42)
